import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MovieService, Movie } from '../../services/movie.service';
import { CinemaService, Cinema, Room } from '../../services/cinema.service';
import { FilmShowService, FilmShow } from '../../services/filmShow.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-add-seans',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './add-seans.component.html',
  styleUrls: ['./add-seans.component.less']
})
export class AddSeansComponent implements OnInit {
  seansForm: FormGroup;
  movie: Movie | null = null;
  cinemas: Cinema[] = [];
  rooms: Room[] = [];

  constructor(
    private route: ActivatedRoute,
    private movieService: MovieService,
    private cinemaService: CinemaService,
    private filmShowService: FilmShowService,
    private fb: FormBuilder,
    private router: Router
  ) {
    this.seansForm = this.fb.group({
      date: ['', Validators.required],
      time: ['', Validators.required],
      hall: ['', Validators.required],
      cinema: ['', Validators.required],
      movie: ['']
    });
  }

  ngOnInit(): void {
    const movieId = this.route.snapshot.paramMap.get('id');
    if (movieId) {
      this.movieService.getMovieById(movieId).subscribe((movie: Movie) => {
        this.movie = movie;
        this.seansForm.patchValue({ movie: movie.title });
      });
    }

    this.cinemaService.getCinemas().subscribe((cinemas: Cinema[]) => {
      this.cinemas = cinemas;
    });

    this.seansForm.get('cinema')?.valueChanges.subscribe(cinemaId => {
      this.updateRooms(cinemaId);
    });
  }

  updateRooms(cinemaId: number): void {
    const selectedCinema = this.cinemas.find(cinema => cinema.id == cinemaId);
    console.log('cinemaId:', cinemaId);
    console.log('selectedCinema:', selectedCinema);
    console.log('All Cinemas:', this.cinemas);
    this.rooms = selectedCinema ? selectedCinema.roomList : [];
    this.seansForm.patchValue({ hall: '' });
  }

  onSubmit(): void {
    if (this.seansForm.valid) {
       const formValue = this.seansForm.value;
      const filmShowData: FilmShow = {
        id: 0, // assuming it will be auto-generated by the backend
        dateTime: `${formValue.date}T${formValue.time}`,
        cinemaId: formValue.cinema,
        filmId: this.movie?.id || '', // id filmu
        roomId: formValue.hall,
        availableSeats: this.rooms.find(room => room.id == formValue.hall)?.seats || 0
      };

      this.filmShowService.addFilmShow(filmShowData).subscribe(
        (response: FilmShow) => {
          console.log('Film show added successfully', response);
          this.router.navigate(['/admin-page/movieList']);
        },
        (error: any) => {
          console.error('Error adding film show', error);
        }
      );
    }
  }
}
